# Generated by Django 4.2.7 on 2023-11-29 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_kelas', models.CharField(max_length=200)),
                ('tanggal_kelas', models.DateField()),
                ('harga_kelas', models.IntegerField(default=0)),
                ('mentor_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.mentor')),
            ],
        ),
    ]
