# Generated by Django 4.2.7 on 2023-12-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentee', '0001_initial'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_kelas', models.CharField(max_length=200)),
                ('tanggal_kelas', models.DateField()),
                ('harga_kelas', models.IntegerField(default=0)),
                ('kapasitas_maksimal', models.IntegerField(default=1)),
                ('jumlah_mentee', models.IntegerField(default=0)),
                ('mentee_kelas', models.ManyToManyField(blank=True, related_name='kelas_diikuti', to='mentee.mentee')),
                ('mentor_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='FormJoinKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_bukti_pembayaran', models.URLField()),
                ('status_pembayaran', models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Menunggu Konfirmasi', 'Menunggu Konfirmasi'), ('Pembayaran Diterima', 'Pembayaran Diterima'), ('Pembayaran Ditolak', 'Pembayaran Ditolak'), ('Kelas Gratis', 'Kelas Gratis')], default='Menunggu Pembayaran', max_length=20)),
                ('tanggal_pendaftaran', models.DateTimeField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelas.kelas')),
                ('pendaftar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentee.mentee')),
            ],
        ),
    ]
