# Generated by Django 4.2.7 on 2023-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='jumlah_mentee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kelas',
            name='kapasitas_maksimal',
            field=models.IntegerField(default=1),
        ),
    ]
