# Generated by Django 4.2.7 on 2023-12-04 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
        ('mentor', '0003_initial'),
        ('kelas', '0002_kelas_jumlah_mentee_kelas_kapasitas_maksimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='mentee_kelas',
            field=models.ManyToManyField(blank=True, related_name='kelas_diikuti', to='mentee.mentee'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='mentor_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor'),
        ),
        migrations.CreateModel(
            name='FormJoinKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_bukti_pembayaran', models.URLField()),
                ('status_pembayaran', models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Menunggu Konfirmasi', 'Menunggu Konfirmasi'), ('Pembayaran Diterima', 'Pembayaran Diterima'), ('Pembayaran Ditolak', 'Pembayaran Ditolak'), ('Kelas Gratis', 'Kelas Gratis')], default='Menunggu Pembayaran', max_length=20)),
                ('tanggal_pendaftaran', models.DateTimeField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelas.kelas')),
                ('pendaftar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentee.mentee')),
            ],
        ),
    ]
