# Generated by Django 4.2.7 on 2023-12-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mentee", "0001_initial"),
        ("kelas", "0003_kelas_mentee_kelas_alter_kelas_mentor_kelas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("review_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_kelas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kelas.kelas"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="mentee.mentee",
                    ),
                ),
            ],
        ),
    ]
