# Generated by Django 4.2.7 on 2023-12-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kelas", "0001_initial"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewed_kelas",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_kelas",
                to="kelas.kelas",
            ),
        ),
    ]
