# Generated by Django 4.2.7 on 2023-11-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("1", "Mentor"), ("2", "Mentee")], default="3", max_length=1
            ),
        ),
    ]
