# Generated by Django 4.2.7 on 2023-11-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
