# Generated by Django 4.2.7 on 2023-12-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
    ]
