# Generated by Django 4.2.7 on 2023-12-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_alter_user_profile_picture_alter_user_role'),
        ('authuser', '0005_delete_mentor'),
    ]

    operations = [
    ]
