# Generated by Django 4.2.7 on 2023-11-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
