# Generated by Django 4.2.7 on 2023-12-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminreview', '0001_initial'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor'),
        ),
    ]
