# Generated by Django 4.2.7 on 2023-12-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kelas", "0002_alter_kelas_mentee_kelas"),
        ("adminreview", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materi",
            name="mentor",
        ),
        migrations.AddField(
            model_name="materi",
            name="kelas",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="kelas.kelas"
            ),
        ),
    ]
